package cloudmetrics

import (
	"github.com/prometheus/client_golang/prometheus"
)

const (
	exporterPrometheusRemoteWrite = "prometheus_remote_write"
	exporterOTLP                  = "otlp"
)

// Cloud metrics are billing signals for Valora Cloud; keep them aggregated and non-PII.
type metrics struct {
	usageEvents         *prometheus.CounterVec
	invoicesGenerated   *prometheus.CounterVec
	activeSubscriptions *prometheus.GaugeVec
	engineErrors        *prometheus.CounterVec
}

func newMetrics(registry *prometheus.Registry) *metrics {
	usageEvents := prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "valora_usage_events_total",
		Help: "Usage events successfully processed by the billing engine.",
	}, []string{"organization", "meter"})

	invoicesGenerated := prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "valora_invoices_generated_total",
		Help: "Invoices generated by the billing engine.",
	}, []string{"organization"})

	activeSubscriptions := prometheus.NewGaugeVec(prometheus.GaugeOpts{
		Name: "valora_active_subscriptions",
		Help: "Active subscriptions at billing cycle close or sync.",
	}, []string{"organization"})

	engineErrors := prometheus.NewCounterVec(prometheus.CounterOpts{
		Name: "valora_engine_errors_total",
		Help: "Billing engine errors by operation.",
	}, []string{"organization", "operation"})

	registry.MustRegister(usageEvents, invoicesGenerated, activeSubscriptions, engineErrors)

	return &metrics{
		usageEvents:         usageEvents,
		invoicesGenerated:   invoicesGenerated,
		activeSubscriptions: activeSubscriptions,
		engineErrors:        engineErrors,
	}
}
